version: '3'
services:
    app:
      container_name: java
      restart: always
      build: ./
      ports:
        - '5000:5000'
      links:
        - mongodb
    mongodb:      
      image: mongo
      ports: 
        - '27017:27017'